### ISSUE TITLE
Consider moving this repo and emberjs-times-tools to ember-learn org

### ISSUE THREAD

**Issue by amyrlam** [ember-learn/whats-new-in-emberland#10]
https://github.com/jessica-jordan/emberjs-times-tools

Relates to: https://github.com/jessica-jordan/whats-new-in-emberland/issues/9

**Comment by jessica-jordan** [comment]
That sounds like a great idea :sparkles:

**Comment by jessica-jordan** [comment]
Here we go:
- https://github.com/ember-learn/whats-new-in-emberland
- https://github.com/ember-learn/emberjs-times-tools
