### ISSUE TITLE
Investigate contributors list

### ISSUE THREAD

**Issue by amyrlam** [ember-learn/whats-new-in-emberland#28]
- [ ] Fix contributors list, doesn't include @ Imon-Haque or @ aklkv. Perhaps extend by one day to catch overlap(?) https://github.com/ember-learn/ember-blog/pull/208#issuecomment-517875359
- [ ] Recently @jaredgalanis contributed to deprecations-app, but it didn't show up in the Times. Was it missed because merged Thurs / Fri, or is the repo not included / other bug?

**Comment by amyrlam** [comment]
I manually added https://github.com/aklkv to https://github.com/ember-learn/ember-blog/pull/220, didn't show up last week or this week. cc @jessica-jordan

**Comment by jaredgalanis** [comment]
Closed by #34
