### ISSUE TITLE
Other things to update

### ISSUE THREAD

**Issue by amyrlam** [ember-learn/whats-new-in-emberland#47]
- [ ] Write notes for tmrw to cover the todos, most are Goodbits gotchas that can go away 

//

- [ ] Update readmes tmrw for whatever's missing 

//

- [ ] With new service such as TinyLetter, check that from email address etc matches goodbits and check is not marked as spam. Abhilash and I did _some_ testing of this but ideally we should test with the times team / learning team / as many folks as we can get

**Comment by ijlee2** [comment]
I made a separate issue for adding an "add" so I removed one of the TODO items in this issue.

**Comment by amyrlam** [comment]
Let's use https://github.com/ember-learn/ember-blog/issues/734, which is on https://github.com/orgs/ember-learn/projects/18. Moving off Goodbits is the most important todo for me!
