### ISSUE TITLE
Allow main container to reach full height

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/whats-new-in-emberland#59]
## Problem

When there isn't enough content on a page (this can happen in both `index` and `pull-requests` routes), the user sees a "chopped" screen because the main container didn't get full height (100% of the available screen height).

- `index` route

    <img width="640" alt="Screen Shot 2020-09-19 at 1 47 47 PM" src="https://user-images.githubusercontent.com/16869656/93687116-d8e70c80-fa80-11ea-9108-bbfaa266a4ff.png">

- `pull-requests` route:

    <img width="640" alt="Screen Shot 2020-09-19 at 1 47 57 PM" src="https://user-images.githubusercontent.com/16869656/93687117-da183980-fa80-11ea-843c-0fb23fcd2375.png">

## TODOs

- [ ] Update `application.hbs` and `app.css` so that the main container gets full height. Check that it does by running the app locally.

- [ ] If possible, check that the full height solution also works on mobile. (Some browsers may add menu buttons, which can mess with height calculation.)

## References

- https://github.com/ijlee2/ember-container-query/blob/main/tests/dummy/app/styles/app.css#L1-L19
- https://medium.com/@prowe214/tip-how-to-view-localhost-web-apps-on-your-phone-ad6b2c883a7c

**Comment by aditimaurya** [comment]
Hey, I would like to resolve this issue. if you haven't assigned this to anyone then can I work on this?

**Comment by ijlee2** [comment]
Hi, @aditimaurya. Thanks for taking an interest in helping out with this issue! Yep, I can assign the issue to you to work on.

I created the issue for [Hacktoberfest](https://hacktoberfest.digitalocean.com/), which will begin in 10 days. If you wanted to participate in the event, would you like to wait on working on a solution until October 1st?

In the meantime, I'd suggest trying out:

- Cloning the repo
- Creating a GitHub personal access token with correct read permission
- Running the Ember app locally to see if you can search for contributors

Trying out these steps would help us discover early issues a new contributor might face during Hacktoberfest. ✨

**Comment by aditimaurya** [comment]
@ijlee2 I'm planning to take part in hactoberfest, thanks a lot for assigning this to me. In the mean time, before the fest start I'll read the guidelines once again and try to dig deeper into this project so that I can contribute mre efficiently.

**Comment by ijlee2** [comment]
Awesome, thanks again!

**Comment by aditimaurya** [comment]
@ijlee2  Can you please help me with installations, because I'm not able to run the code an see the website and hence not able to propose any changes, 
I've read the read me, tried to install the same but things are getting very complicated. Can you please guide me? Being very honest, I'm a beginner so maybe that's why facing issues. I hope you'll help me with that.

**Comment by ijlee2** [comment]
@aditimaurya Yep, I'm happy to help! Let me reply with another message for more detailed installation instructions.

To confirm, were you able to run an Ember app before (e.g. for work or hobby project) but you were having trouble with running _this_ particular app? I was wondering if you installed Node.js (v12 or v14 recommended), npm, and Ember CLI already. For more information on installing these 3, you can visit:

https://guides.emberjs.com/release/getting-started/quick-start/#toc_install-ember

**Comment by aditimaurya** [comment]
Hey, I've installed all of them, and also generated a token, but I'm facing problems when it comes to run "yarn". My IDE or cmd prompt is not taking the command "install yarn" or "yarn install". And so I'm not able to proceed further. 
I haven't used emberland before, I'm just trying to learn new things and exploring open-source community to work.
I hope this information might help you to get what issues I'm facing.

**Comment by ijlee2** [comment]
> Hey, I've installed all of them, and also generated a token, but I'm facing problems when it comes to run "yarn". My IDE or cmd prompt is not taking the command "install yarn" or "yarn install". And so I'm not able to proceed further.
I haven't used emberland before, I'm just trying to learn new things and exploring open-source community to work.
I hope this information might help you to get what issues I'm facing.

Yep, that information was perfect! I appreciate your explaining the steps that you've tried. It helps help a maintainer understand whether their assumptions about a project were correct.

In general, you will find that Ember apps and addons rely on either `npm` or `yarn` to manage the packages (libraries) that they installed. You can guess which package manager to use in 2 ways:

- The project's `README` (or maybe `CONTRIBUTING`) file mentions `npm` or `yarn` in the installation step.
- You can see `package-lock.json` file if the project used `npm`, or `yarn.lock` file if the project used `yarn`.

`whats-new-in-emberland` uses `yarn`, so let's first check that you have `yarn` installed on your computer. I think, if you do have `yarn`, then you will see a version number when you run the following command in your terminal:

```bash
# Try running:
yarn --version

# Output may look something like:
1.22.5
```

If you get an error version instead, I think it's possible that you currently don't have `yarn` installed and need to. For more information on installing yarn, I recommend following the steps described in https://classic.yarnpkg.com/en/docs/install . The website will tell you what you need to do for a given OS (operating system).

Can you try installing `yarn` and let me know how it went?

**Comment by ijlee2** [comment]
I've updated the installation instructions in README. Hope they are a little more clear.

If you have additional questions, please feel free to ask. Thanks!

https://github.com/ember-learn/whats-new-in-emberland#installation

**Comment by ijlee2** [comment]
Hi, @aditimaurya. I want to check in to see if you were able to get the repo locally installed and running. Please feel free to let us know if you need additional help.

This Saturday (Oct 10) at 9 am and 9 pm EST, you can join a live mentoring event. Please check the `#hacktoberfest` channel on [Ember Discord](https://discord.gg/emberjs) for more information!

**Comment by aditimaurya** [comment]
Hi @ijlee2 , sorry I got busy with my exams so not able to make time. I'll try to follow up the guidelines again tomorrow and will let you know if I'll face any difficulty. I'll surely join the event on Saturday 🎉 
Thanks a lot for your invitation!!!! 
( I've joined the discord , thanks again)

**Comment by ijlee2** [comment]
Thanks for a quick reply, I hope your exams went well! Please feel free to give priority to your studies.

Cheers,
