### ISSUE TITLE
GitHub auth token change

### ISSUE THREAD

**Issue by amyrlam** [ember-learn/whats-new-in-emberland#79]
I can't get past this 401 error. I had gotten an email recently, about GitHub changing the auth tokens. I'm going to contact their support, after sending out the Times, and we could do a month's of contributors next issue. Trying a bit longer to figure out the curl though.

Anyone else happen to have this repo working by chance? @ijlee2 @ember-learn/ember-times-editors 

![image](https://user-images.githubusercontent.com/1372946/122629781-56719480-d074-11eb-8ab4-a194610f0ba0.png)

**Comment by amyrlam** [comment]
Noting for debugging later:

```
curl -XGET -H "Accept: application/vnd.github.v3+json" -H"authorization: Bearer <my-new-token>" https://api.github.com/search/issues?q=is:pr+org:ember-learn+created:%3E=2021-06-04

zsh: no matches found: https://api.github.com/search/issues?q=is:pr+org:ember-learn+created:%3E=2021-06-04
```

**Comment by ijlee2** [comment]
@amyrlam Thanks for writing a report of the bug and attaching a screenshot. I remember getting an email from GitHub some time ago, but forgot to act on it. I can help you by having a look at the repo today.

**Comment by ijlee2** [comment]
@amyrlam I ran the app locally and got the contributors list without any change to codebase or token. Perhaps you need to regenerate a token so that it's new?

**Comment by amyrlam** [comment]
@ijlee2 Thanks a lot for chiming in. It's really strange because I didn't change the token last issue, and tried it first without changing it first yesterday. I also didn't even have the token in my `.env` before. So confuse all around!

**Comment by ijlee2** [comment]
@amyrlam Can you try creating `.env`, then storing the personal token as shown in `.env-sample` (this file won't be committed, no worries)? If you're still unable to get the contributors list, we can look further into debugging.

https://github.com/ember-learn/whats-new-in-emberland#setup

**Comment by amyrlam** [comment]
Sorry for the confusion, I had done that yesterday (made a .env) in debugging. Just was weird it had worked before, with the old token, when it wasn't in the .env 🤷‍♀️

**Comment by amyrlam** [comment]
@ijlee2 thanks again, I'm on a new machine, talked to support, and it works now! 🤷‍♀️
